### ISSUE TITLE
请问我执行训练的时候报No module named 'rasa_nlu_gao.extractors.hanlp_extractor' 怎么解决。

### ISSUE THREAD

**Issue by myongyun** [algteam/rasabot#1]
PS C:\Users\60348\Desktop\rasabot-hanlp\rasabot-master\rasa-nlu-example> python train_nlu.py
Traceback (most recent call last):
  File "train_nlu.py", line 21, in <module>
    model_directory = Train_nlu(nlu_file, config_file)
  File "train_nlu.py", line 12, in Train_nlu
    trainer = Trainer(config.load(config_file))
  File "C:\Users\60348\Anaconda36\lib\site-packages\rasa_nlu\model.py", line 152, in __init__
    components.validate_requirements(cfg.component_names)
  File "C:\Users\60348\Anaconda36\lib\site-packages\rasa_nlu\components.py", line 49, in validate_requirements
    from rasa_nlu import registry
  File "C:\Users\60348\Anaconda36\lib\site-packages\rasa_nlu\registry.py", line 36, in <module>
    from rasa_nlu_gao.extractors.hanlp_extractor import HanlpExtractor  # customize
ModuleNotFoundError: No module named 'rasa_nlu_gao.extractors.hanlp_extractor'

**Comment by myongyun** [comment]
对python不是很熟悉 ，，， 已经解决
